# MongoDB 配置
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/spring4demo}
      database: ${MONGODB_DATABASE:spring4demo}
      auto-index-creation: true
      auto-time-logs: true