# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 动态数据源配置
    dynamic:
      enabled: true
      strict: false
      primary: master
      datasource:
        master:
          name: master
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${DATASOURCE_MASTER_URL:jdbc:mysql://localhost:3306/junmo_platform?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true}
          username: ${DATASOURCE_MASTER_USERNAME:junmo_platform}
          password: ${DATASOURCE_MASTER_PASSWORD:junmo_platform}
          type: com.alibaba.druid.pool.DruidDataSource
          primary: true
          druid:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            max-evictable-idle-time-millis: 900000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat,wall
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            stat-view-servlet-enabled: true
            stat-view-servlet-url-pattern: /druid/*
            stat-view-servlet-login-username: ${DRUID_STAT_USERNAME}
            stat-view-servlet-login-password: ${DRUID_STAT_PASSWORD}
            web-stat-filter-enabled: true
            web-stat-filter-url-pattern: /*
            web-stat-filter-exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        slave:
          name: slave
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${DATASOURCE_SLAVE_URL:jdbc:mysql://localhost:3307/junmo_platform?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true}
          username: ${DATASOURCE_SLAVE_USERNAME:junmo_platform}
          password: ${DATASOURCE_SLAVE_PASSWORD:junmo_platform}
          type: com.alibaba.druid.pool.DruidDataSource
          readonly: true
          druid:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            max-evictable-idle-time-millis: 900000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat,wall
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            stat-view-servlet-enabled: true
            stat-view-servlet-url-pattern: /druid/*
            stat-view-servlet-login-username: ${DRUID_STAT_USERNAME}
            stat-view-servlet-login-password: ${DRUID_STAT_PASSWORD}
            web-stat-filter-enabled: true
            web-stat-filter-url-pattern: /*
            web-stat-filter-exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'